services:
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    profiles: [production]
    depends_on:
      - django
    command: daemon --docker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    profiles: [production]
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    volumes:
      - certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
    #  - /etc/acme.sh
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - static:/static/
    networks:
      - backend
      - frontend
    ports:
      - '80:80'
      - '443:443'
    restart: always

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    profiles: [production]
    environment:
      - LETSENCRYPT_EMAIL=kristina.trinity@anymouse.org
      - LETSENCRYPT_HOST=zpe.anymouse.org
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy
    networks:
      - frontend
    restart: unless-stopped
    depends_on:
      - nginx-proxy

  django:
    build:
      context: .
      dockerfile: ./config/backend/Dockerfile
    profiles: [production]
    environment:
    - PRODUCTION=true
    volumes:
    - .:/code
    - ./db:/db
    - static:/static/
    - shared-volume:/tmp/downloads
    networks:
    - backend
    ports:
    - "8000:8000"
    restart: unless-stopped
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.fetch.schedule: "@daily"
      ofelia.job-exec.fetch.command: "python /code/planning_notifier/manage.py fetch_cases"
      ofelia.job-exec.fetch.no-overlap: "true"
    depends_on:
    - selenium
    #   - nginx-proxy

  django-dev:
    build:
      context: .
      dockerfile: ./config/backend/Dockerfile-local
    profiles: [debug]
    environment:
    - PRODUCTION=false
    volumes:
    - .:/code
    - ./db:/db
    - static:/static/
    - shared-volume:/tmp/downloads
    networks:
    - backend
    ports:
    - "8000:8000"
    restart: unless-stopped
    labels:
      ofelia.enabled: "false"
      ofelia.job-exec.fetch.schedule: "@daily"
      ofelia.job-exec.fetch.command: "python /code/planning_notifier/manage.py fetch_cases"
      ofelia.job-exec.fetch.no-overlap: "true"
    depends_on:
    - selenium
    #   - nginx-proxy


  selenium:
    image: selenium/standalone-firefox:4.27.0-20241204
    shm_size: 2gb
    profiles: [production, debug]

    networks:
      - frontend
      - backend
    ports:
      - "127.0.0.1:4444:4444"
      - "127.0.0.1:7900:7900"
    environment:
    #      - SE_START_XVFB=false
      - SE_ENABLE_TRACING=false
    volumes:
      - shared-volume:/home/seluser/Downloads

networks:
  frontend:
  backend:

volumes:
  shared-volume:
  db:
  static:
  certs:
  acme:
