# Generated by Django 5.1.1 on 2024-10-11 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_cases', '0002_alter_planning_case_case_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning_case',
            name='case_date',
            field=models.DateField(default='2024-10-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planning_case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planning_case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
