# Generated by Django 5.1.1 on 2024-10-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_cases', '0006_area_of_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='area_of_interest',
            name='planning_cases',
            field=models.ManyToManyField(to='planning_cases.planning_case'),
        ),
    ]
