# Generated by Django 5.1.1 on 2024-12-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_cases', '0007_area_of_interest_planning_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area_of_interest',
            name='notes',
        ),
        migrations.AlterField(
            model_name='area_of_interest',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
