# Generated by Django 5.1.4 on 2024-12-20 18:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_cases', '0010_remove_area_of_interest_planning_cases_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='planning_case',
        #     name='geometry_pnt',
        #     field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        # ),
        # migrations.AlterField(
        #     model_name='planning_case',
        #     name='geometry_poly',
        #     field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        # ),
    ]
