# Generated by Django 5.1.4 on 2024-12-20 18:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_cases', '0011_alter_planning_case_geometry_pnt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning_case',
            name='geometry_poly',
        ),
        migrations.AlterField(
            model_name='planning_case',
            name='geometry_pnt',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
