# Generated by Django 5.1.4 on 2025-01-11 18:46

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('planning_cases', '0001_initial'), ('planning_cases', '0002_alter_planning_case_case_type_and_more'), ('planning_cases', '0003_planning_case_case_date_planning_case_created_at_and_more'), ('planning_cases', '0004_alter_planning_case_description_and_more'), ('planning_cases', '0005_planning_case_parcel_number_and_more'), ('planning_cases', '0006_area_of_interest'), ('planning_cases', '0007_area_of_interest_planning_cases'), ('planning_cases', '0008_remove_area_of_interest_notes_and_more'), ('planning_cases', '0009_alter_area_of_interest_planning_cases'), ('planning_cases', '0010_remove_area_of_interest_planning_cases_and_more'), ('planning_cases', '0011_alter_planning_case_geometry_pnt_and_more'), ('planning_cases', '0012_remove_planning_case_geometry_poly_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='planning_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(blank=True, max_length=200)),
                ('case_number', models.CharField(max_length=30, unique=True)),
                ('location', models.TextField(blank=True, max_length=1024)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('owner', models.CharField(blank=True, max_length=1024)),
                ('case_url', models.URLField(blank=True)),
                ('geometry_pnt', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('case_date', models.DateField(default='2024-10-11')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='area_of_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
