# Generated by Django 5.1.1 on 2024-10-01 23:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='planning_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=200)),
                ('case_number', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('owner', models.CharField(max_length=1024)),
                ('case_url', models.URLField(blank=True)),
                ('geometry_pnt', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
            ],
        ),
    ]
