# Generated by Django 5.1.4 on 2025-01-11 19:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_cases', '0001_squashed_0012_remove_planning_case_geometry_poly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning_case',
            name='geometry_poly',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='planning_case',
            name='case_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='planning_case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='planning_case',
            name='geometry_pnt',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
